language: node_js
node_js:
  - "5.1"

addons:
  sauce_connect: true
  # Node 5 requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8 # This is linked to the issue above with Node 5
    # Firebase
    - secure: "SrM3vnVd03xvNZlb/uGASA9Cmb42OGo5H5vodtFZxx6Ie9v6nQ0mewZCNpJ7UE3bSm7Zx6mA1olOTWGo7SkgyqUR3RPTwQCXCq1ovJ+p6JfXs+FHYA4r4I7b7Lawf2UggangDCei70KeB9MxW3VQQ216v7KDFYySq3HqcUcEvDcPB2qtAC+SCA7qr+HQPuour+U/IT90L5FbI+d1dJlBPmD58V/EOTpp5OgNKxx80/nXa5gAmFcARf/OhGXmb43heBYH2ElryFqygmvg35namXcYbyns9L5+MjKRZvAwiuTD9i6+FwWyLNsuLRw74AooQk6WZERfvIB8Jjwc3WojZTW8ITXuQgYxLqYhL8vEZIrkyTU8VI5RrKgGp4MfF5YoDT9nfucFFCbzBRk11mPUVla89+utMNrvWHm6uKBBVMrSCaCidzUpOCAec2bT4VPp5ZBIYK4pbMLZaJ/Y4K15ejyKgQJteMZ/rrZxDUJ6TPBqcqINZ+9q3baEB4kCzQv5Q2YdkeGduxCDycWlOeMB1N5YrdNczKBeQT3xbHftkLhrW6K433xVd2GbGbgbxoqb4BLuVBxKzNPQLb9QTzZrCj7rmMrfNasMlvE2CPf6Y8TnnZlAaAuZZxXB65XIEIvzj+dfMLkB9Cl4IhFgw9NE8f1xr0CMU/1jRh6diIlP67o="
    # Saucelabs
    - SAUCE_USERNAME=rolandjitsu
    - secure: "JCabDo1wjn+rcfl9R3lXnF0XqPn5xOcm4zUo0+dSAgMiv+/3mC38KGo/fvbsdQzyxTU3hrYUOYk3cp/iI6MQE/h+u/sD0Ixo1B77inGZarSiQqyh93lDPF02NBziwWKOw/KA9PGehlE6SZ4qa55V4A3iOV4+fbwHGzmr/I9QNomAKybAiHrBx/1yA5Q8mFD9AtSgeP9f9vGFqFFFPJIikHdNQL4kF/PoDrn763jHLFVdk1BFd8U/ZV61fArtfxvb1ySMZuIp6GVvOjbDp/hG4hCdcuWiSF0TGQWcvxrzty26mP5qh75yKu9G28l7ln1PLqN/xLEDX7Bv2O5v57eeAGVh49AJjAab3brm69L6KOdJdOnYpCTb6ssrajJMCv+10UV97PYt8yYsUsn+Kg8f8jB0qOHeFwGX0EE9xNKXJOORjRt9gIg/H71XBGXQCMnqHWU2/3NY4XcT6aj4NNv8PkdxXkgV1x2HXs7MqUIk4pfhV+RJd9pbK0WaKc9sAOydyYW+ziEZXk6vCXnTlVoCuCzAFOx74OTuwk0fmNRD8knMW++evyImd5aSc6ENGhvu7MTUehfNSTH+fCSZhT1Ao1E2pSrOAWYl0wHBPPNRsQNEHf7MrzcWB42uM3icPsmoKZHs7+UB+lmY0ejxkI/jj8U2+BBVtf+QthETCDLj1k4="

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install --loglevel silent
  - $(npm bin)/jspm install
  - $(npm bin)/typings install

before_script: ./scripts/ci/clean.sh

script:
  - ./scripts/ci/build.sh
  - ./scripts/ci/test.sh

after_success: ./scripts/ci/deploy.sh
after_script: ./scripts/ci/clean.sh

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e8e1d417898b5281d968
    on_success: change
    on_failure: always
    on_start: never