language: node_js
node_js:
  - "7.4"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  sauce_connect: true
  # Node 5+ requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8 # This is linked to the issue above with Node 5
    # Firebase
    - secure: "HrNS34+bm/Nes7Fj9PsJHWqQ4SXFioPNwKKsODkMNMKomLmOkUaQGZJOE7AoUcxfPV5+9wAkFV1rNnZnH5yvPcwx4y42MGsdR2koZ+BYl+s+qSXgQf637owCz6/gj4A8X7vdG10Nhac+oPoqJCsmoJBr1hoJTi0OaTxyvzL5F83XmtbLqzE2GGYhaHYskAzxplG1EZMzECn3fI874Q+QpqKPCqXj+9/IMNqxZN1sEnYhRyOgg5FvbHPR8RNcSAYhiTMrkD1rQuZgK+hJVHy2HKuL5YdkDXtbmQfGtrvL7XiScwBPOs7SpzcONUHxKB9vaMZ/6goDjYSg8BlD7JBvatgTCP8uMhG0yIS6nxXPf/h6wArhjcioikxZn+rxSsABJeu0SM3sDr5JjQjE0lJzCnFym713NpdK+dLoWVy+TSGD/XV5kSTdVZ1x8VT/J+Ddje6ezK3L/B22ha0UYHt/1Nsr2A2bOyyiO1JrJEPz/MLHfrAi616gHvVJ8czPLCyykki25Xljs7EnnFP6FM/+Qi338ajvFPJIc+MD+6P97HDO2iGlRra/UnsDjRL2ZxQjqMkVXMlvNZP6+qgqD6Z6jmhNuxOlPKVPQHC9MNTviJX90u3oOCvhzq4Y37joSffHJtMB3IusRUjo18KpvFg584NxzpaTWMCgdKF/tvX8dZA="
    # Saucelabs
    - SAUCE_USERNAME=rolandjitsu
    - secure: "JCabDo1wjn+rcfl9R3lXnF0XqPn5xOcm4zUo0+dSAgMiv+/3mC38KGo/fvbsdQzyxTU3hrYUOYk3cp/iI6MQE/h+u/sD0Ixo1B77inGZarSiQqyh93lDPF02NBziwWKOw/KA9PGehlE6SZ4qa55V4A3iOV4+fbwHGzmr/I9QNomAKybAiHrBx/1yA5Q8mFD9AtSgeP9f9vGFqFFFPJIikHdNQL4kF/PoDrn763jHLFVdk1BFd8U/ZV61fArtfxvb1ySMZuIp6GVvOjbDp/hG4hCdcuWiSF0TGQWcvxrzty26mP5qh75yKu9G28l7ln1PLqN/xLEDX7Bv2O5v57eeAGVh49AJjAab3brm69L6KOdJdOnYpCTb6ssrajJMCv+10UV97PYt8yYsUsn+Kg8f8jB0qOHeFwGX0EE9xNKXJOORjRt9gIg/H71XBGXQCMnqHWU2/3NY4XcT6aj4NNv8PkdxXkgV1x2HXs7MqUIk4pfhV+RJd9pbK0WaKc9sAOydyYW+ziEZXk6vCXnTlVoCuCzAFOx74OTuwk0fmNRD8knMW++evyImd5aSc6ENGhvu7MTUehfNSTH+fCSZhT1Ao1E2pSrOAWYl0wHBPPNRsQNEHf7MrzcWB42uM3icPsmoKZHs7+UB+lmY0ejxkI/jj8U2+BBVtf+QthETCDLj1k4="

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn

#before_script: ./scripts/ci/clean.sh

script:
  # Code style/format check with tslint.
  - npm run lint
  # Unit tests.
  - npm run test:ci
  # E2E tests.
  - npm run e2e:ci

after_success: ./scripts/ci/deploy.sh

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e8e1d417898b5281d968
    on_success: change
    on_failure: always
    on_start: never
